apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-server
  labels:
    app: spark-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-server
  template:
    metadata:
      labels:
        app: spark-server
    spec:
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
      - name: secret-volume
        secret:
          secretName: bigquery-credentials
      containers:
      - image: gcr.io/spark-container-testing/client-mode-spark-notebook:latest
        name: client-mode-spark-notebook
        volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /var/secrets/google    
